=== qubitsSuperPosition/rep/bryans-cafe/data/menu.dtd
<!ELEMENT menu (meals, hotBeverages, otherBeverages)>
<!ELEMENT meals (meal+)>
<!ELEMENT meal (name, price, description, image)>
<!ELEMENT hotBeverages (beverage+)>
<!ELEMENT otherBeverages (beverage+)>
<!ELEMENT beverage (size?, name?, price, description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>

=== qubitsSuperPosition/rep/bryans-cafe/data/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <meals>
        <meal>
            <name>Beetroot and Feta Salad</name>
            <price>$15.00</price>
            <description>Suitable for vegetarians, made with fresh beetroot</description>
            <image>../assets/images/beetroot.webp</image>
        </meal>
        <meal>
            <name>Sourdough Rye Sandwich</name>
            <price>$18.00</price>
            <description>Cheese and salad sandwich made with organic sourdough rye bread</description>
            <image>../assets/images/Sandwich.webp</image>
        </meal>
        <meal>
            <name>Spinach Pie and Salad</name>
            <price>$20.00</price>
            <description>Tasty pie with fresh salad</description>
            <image>../assets/images/pie.webp</image>
        </meal>
        <meal>
            <name>Feta Pancakes with Salad</name>
            <price>$19.50</price>
            <description>Tasty pancakes filled with feta and served with a side of fresh salad</description>
            <image>../assets/images/Pancakes.webp</image>
        </meal>
    </meals>

    <hotBeverages>
        <beverage>
            <size>Small</size>
            <price>$3.50</price>
            <description>For coffee, please inform the staff of the coffee type</description>
        </beverage>
        <beverage>
            <size>Regular</size>
            <price>$4.00</price>
            <description>For coffee, please inform the staff of the coffee type</description>
        </beverage>
        <beverage>
            <size>Large</size>
            <price>$4.50</price>
            <description>For coffee, please inform the staff of the coffee type</description>
        </beverage>
    </hotBeverages>

    <otherBeverages>
        <beverage>
            <name>Soda</name>
            <price>$3.00</price>
        </beverage>
        <beverage>
            <name>Fresh Juice</name>
            <price>$6.00</price>
        </beverage>
        <beverage>
            <name>Bottled Water</name>
            <price>$2.00</price>
        </beverage>
    </otherBeverages>
</menu>
